name: Save Log

on:
  workflow_dispatch:
    inputs:
      message:
        description: "メッセージ"
        required: true
        type: string

jobs:
  save:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Append log
        run: |
          echo "$(date) - ${{ github.event.inputs.message }}" >> logs.txt

      - name: Commit and push
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add logs.txt
          git commit -m "Add log"
          git push https://x-access-token:${TOKEN}@github.com/koharoot/koharoot.git HEAD:main
